### ISSUE TITLE
Does not work with k9s@0.30

### ISSUE THREAD

**Issue by mamachanko** [catppuccin/k9s#3]
After upgrading to k9s@0.30.x the catppuccin/k9s skins no longer seem to work. I can't yet tell if there's a change to the skin schema, but k9s' bundled skins work as expected.

This is what it looks like with `k9s.ui.skin: mocha` configured:
![screenshot](https://github.com/catppuccin/k9s/assets/1182927/42e8a8b3-1fe0-4933-83be-2bc9bb11358a)

**Comment by nekowinston** [comment]
Thanks for the update. I'll try to take a look later, but I'd appreciate if someone else could take this up.

**Comment by mamachanko** [comment]
A first superficial experiment suggests that the anchors are not being resolved.

When rendering the contents of `dist/mocha.yaml` before handing it over to k9s it seems to work.

```
ytt -f skins/mocha.yml >skins/mocha_rendered.yml
```

Will see if this is smth k9s should address or we should here.

**Comment by nekowinston** [comment]
> Will see if this is smth k9s should address or we should here.

I reworked the build system so that it's using our [palette](https://github.com/catppuccin/palette) repo, so it's getting rid of anchors that way. Relying on them, and the YAML parser, was always a bit messy. 🙃

**Comment by mamachanko** [comment]
As mentioned over here https://github.com/catppuccin/k9s/pull/4#issuecomment-1875474324 it turned out to be a matter of file extensions. k9s is really picky about `.yaml` and does not want `.yml`.
